// <auto-generated />
using System;
using KartverketWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KartverketWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KartverketWebApp.Data.Ansatt", b =>
                {
                    b.Property<int>("AnsattId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AnsattId"));

                    b.Property<DateTime?>("AnsettelsesDato")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Kommunenummer")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("AnsattId");

                    b.HasIndex("PersonId");

                    b.ToTable("Ansatt");
                });

            modelBuilder.Entity("KartverketWebApp.Data.Bruker", b =>
                {
                    b.Property<int>("BrukerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BrukerId"));

                    b.Property<string>("BrukerType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Passord")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BrukerId");

                    b.ToTable("Bruker");
                });

            modelBuilder.Entity("KartverketWebApp.Data.Kart", b =>
                {
                    b.Property<int>("KartEndringId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KartEndringId"));

                    b.Property<string>("Beskrivelse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Koordsys")
                        .HasColumnType("int");

                    b.Property<string>("MapType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RapportType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SteddataId")
                        .HasColumnType("int");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("KartEndringId");

                    b.HasIndex("SteddataId")
                        .IsUnique();

                    b.ToTable("Kart");
                });

            modelBuilder.Entity("KartverketWebApp.Data.Koordinater", b =>
                {
                    b.Property<int>("KoordinatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KoordinatId"));

                    b.Property<int>("KartEndringId")
                        .HasColumnType("int");

                    b.Property<double>("Nord")
                        .HasColumnType("double");

                    b.Property<double>("Ost")
                        .HasColumnType("double");

                    b.Property<int>("Rekkefolge")
                        .HasColumnType("int");

                    b.HasKey("KoordinatId");

                    b.HasIndex("KartEndringId");

                    b.ToTable("Koordinater");
                });

            modelBuilder.Entity("KartverketWebApp.Data.Meldinger", b =>
                {
                    b.Property<int>("MeldingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MeldingsId"));

                    b.Property<string>("Innhold")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MottakerPersonId")
                        .HasColumnType("int");

                    b.Property<int>("RapportId")
                        .HasColumnType("int");

                    b.Property<int>("SenderPersonId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Tidsstempel")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MeldingsId");

                    b.HasIndex("MottakerPersonId");

                    b.HasIndex("RapportId");

                    b.HasIndex("SenderPersonId");

                    b.ToTable("Meldinger");
                });

            modelBuilder.Entity("KartverketWebApp.Data.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<int?>("BrukerId")
                        .HasColumnType("int");

                    b.Property<string>("Etternavn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PersonId");

                    b.HasIndex("BrukerId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("KartverketWebApp.Data.Rapport", b =>
                {
                    b.Property<int>("RapportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RapportId"));

                    b.Property<int>("KartEndringId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Opprettet")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("RapportStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TildelAnsattId")
                        .HasColumnType("int");

                    b.HasKey("RapportId");

                    b.HasIndex("KartEndringId");

                    b.HasIndex("PersonId");

                    b.HasIndex("TildelAnsattId");

                    b.ToTable("Rapport");
                });

            modelBuilder.Entity("KartverketWebApp.Data.Steddata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fylkenavn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Fylkenummer")
                        .HasColumnType("int");

                    b.Property<string>("Kommunenavn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Kommunenummer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Steddata");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KartverketWebApp.Data.Ansatt", b =>
                {
                    b.HasOne("KartverketWebApp.Data.Person", "Person")
                        .WithMany("Ansatt")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("KartverketWebApp.Data.Kart", b =>
                {
                    b.HasOne("KartverketWebApp.Data.Steddata", "Steddata")
                        .WithOne("Kart")
                        .HasForeignKey("KartverketWebApp.Data.Kart", "SteddataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Steddata");
                });

            modelBuilder.Entity("KartverketWebApp.Data.Koordinater", b =>
                {
                    b.HasOne("KartverketWebApp.Data.Kart", "Kart")
                        .WithMany("Koordinater")
                        .HasForeignKey("KartEndringId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kart");
                });

            modelBuilder.Entity("KartverketWebApp.Data.Meldinger", b =>
                {
                    b.HasOne("KartverketWebApp.Data.Person", "Mottaker")
                        .WithMany()
                        .HasForeignKey("MottakerPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KartverketWebApp.Data.Rapport", "Rapport")
                        .WithMany("Meldinger")
                        .HasForeignKey("RapportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KartverketWebApp.Data.Person", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mottaker");

                    b.Navigation("Rapport");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("KartverketWebApp.Data.Person", b =>
                {
                    b.HasOne("KartverketWebApp.Data.Bruker", "Bruker")
                        .WithMany("Personer")
                        .HasForeignKey("BrukerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bruker");
                });

            modelBuilder.Entity("KartverketWebApp.Data.Rapport", b =>
                {
                    b.HasOne("KartverketWebApp.Data.Kart", "Kart")
                        .WithMany("Rapporter")
                        .HasForeignKey("KartEndringId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KartverketWebApp.Data.Person", "Person")
                        .WithMany("Rapporter")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KartverketWebApp.Data.Ansatt", "TildelAnsatt")
                        .WithMany("Rapporter")
                        .HasForeignKey("TildelAnsattId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kart");

                    b.Navigation("Person");

                    b.Navigation("TildelAnsatt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KartverketWebApp.Data.Ansatt", b =>
                {
                    b.Navigation("Rapporter");
                });

            modelBuilder.Entity("KartverketWebApp.Data.Bruker", b =>
                {
                    b.Navigation("Personer");
                });

            modelBuilder.Entity("KartverketWebApp.Data.Kart", b =>
                {
                    b.Navigation("Koordinater");

                    b.Navigation("Rapporter");
                });

            modelBuilder.Entity("KartverketWebApp.Data.Person", b =>
                {
                    b.Navigation("Ansatt");

                    b.Navigation("Rapporter");
                });

            modelBuilder.Entity("KartverketWebApp.Data.Rapport", b =>
                {
                    b.Navigation("Meldinger");
                });

            modelBuilder.Entity("KartverketWebApp.Data.Steddata", b =>
                {
                    b.Navigation("Kart")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
