#Base image for running the app
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

#Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["KartverketWebApp.csproj", "./"]
RUN dotnet restore "./KartverketWebApp.csproj"
COPY . .
WORKDIR "/src"
RUN dotnet build "./KartverketWebApp.csproj" -c $BUILD_CONFIGURATION -o /app/build

#Publish stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./KartverketWebApp.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

#Final stage
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "KartverketWebApp.dll"]