version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: toppHemmelig007!@
      MYSQL_DATABASE: Kartverketdb
      MYSQL_USER: root
      MYSQL_PASSWORD: toppHemmelig007!@
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  KartverketWebApp:
    image: ${DOCKER_REGISTRY-}kartverkwebapp
    build:
      context: .
      dockerfile: KartverketWebApp/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mariadb
    environment:
      ConnectionStrings__DefaultConnection: "Server=mariadb;Database=Kartverketdb;User=root;Password=toppHemmelig007!@;"
    networks:
      - backend

volumes:
  mariadb_data:

networks:
  backend:
