version: '3.4'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: toppHemmelig007!@
      MYSQL_DATABASE: Kartverketdb
      MYSQL_USER: root
      MYSQL_PASSWORD: nestenHemmelig007!@
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  kartverketwebapp:
    image: ${DOCKER_REGISTRY-}kartverketwebapp
    build:
      context: .  # Ensure this path is correct
      dockerfile: KartverketWebApp/Dockerfile  # Ensure this file exists
    ports:
      - "8080:80"
    depends_on:  # This should be aligned correctly
      - mariadb
    environment:  # This should be aligned correctly
      ConnectionStrings__MariaDbConnection: "Server=mariadb;Database=Kartverketdb;User=root;Password=toppHemmelig007!@;"
    networks:
      - backend

volumes:
  mariadb_data:

networks:
  backend:
