version: '3.4'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: toppHemmelig007!@
      MYSQL_DATABASE: geochangesdb
      MYSQL_USER: root
      MYSQL_PASSWORD: nestenHemmelig007!@
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  KartverketWebApp:
    image: ${DOCKER_REGISTRY-}KartverketWebApp
    build:
      context: .  # Ensure this path is correct
      dockerfile: KartverketWebApp/Dockerfile  # Ensure this file exists
    ports:
      - "8080:80"
    depends_on:  # This should be aligned correctly
      - mariadb
    environment:  # This should be aligned correctly
      ConnectionStrings_defaultConnection: "Server=mariadb;Database=geochangesdb;User=root;Password=nestenHemmelig007!@;"
    networks:
      - backend

volumes:
  mariadb_data:

networks:
  backend:
