name: Generate Changelog

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Generate Changelog
      id: changelog
      uses: mikepenz/release-changelog-builder-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        configuration: |
          {
            "categories": [
              {
                "title": "## 🚀 Nye Funksjoner",
                "labels": ["feature", "enhancement"]
              },
              {
                "title": "## 🐛 Feilrettinger",
                "labels": ["fix", "bug"]
              },
              {
                "title": "## 📝 Dokumentasjon",
                "labels": ["documentation"]
              },
              {
                "title": "## 🔨 Vedlikehold",
                "labels": ["maintenance"]
              }
            ]
          }
        
    - name: Update CHANGELOG.md
      run: |
        echo "${{ steps.changelog.outputs.changelog }}" > CHANGELOG.md
        
    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add CHANGELOG.md
        git commit -m "📝 Oppdatert CHANGELOG.md" || exit 0
        git push